version: "3.9"
services:
  redis: 
    image: redis:latest
    restart: always
    deploy:
      mode: replicated
      replicas: 1
      placement:
        max_replicas_per_node: 1
        constraints:
          - "node.role==manager"
      restart_policy:
        delay: 5s
    networks:
      - ferrum
    logging:
      driver: local

  server:
    image: _PRIVATE_REGISTRY/ferrumgate/secure.server:1.0.0
    restart: always
    ports:
      - '9999:9999'
    environment:
      - REDIS_HOST=redis#6379
      - PORT=9999
      - LOGIN_URL=http://192.168.88.51/login
    cap_add:
      - NET_ADMIN
    deploy:
      mode: global
      restart_policy:
        delay: 5s
    volumes:
      - /dev/net/tun:/dev/net/tun
      - /dev/urandom:/dev/urandom
      - /etc/ferrumgate:/etc/ferrumgate
    networks:
      - ferrum
    logging:
      driver: local

  admin:
    image: _PRIVATE_REGISTRY/ferrumgate/job.admin:1.0.0
    restart: always
    privileged: true
    #cap_add:
    #  - NET_ADMIN
    #  - MKNOD
    environment:
      - REDIS_HOST=redis:6379
    deploy:
      mode: global
      restart_policy:
        delay: 5s
    volumes:
      - /etc/ferrumgate:/etc/ferrumgate
    network_mode: service:server
    logging:
      driver: local



  ui:
    image: _PRIVATE_REGISTRY/ferrumgate/ui.portal:1.0.0
    restart: always
    deploy:
      restart_policy:
        delay: 5s
    networks:
      - ferrum
    logging:
      driver: local

  rest:
    image: _PRIVATE_REGISTRY/ferrumgate/rest.portal:1.0.0
    restart: always
    environment:
      - PORT=8181
      - REDIS_HOST=redis:6379
      - BASE_RATE_LIMIT=25
      - ENCRYPT_KEY=rktIuxHZLZXXRFFrPtTLxYHyFWZcsoef
    deploy:
      restart_policy:
        delay: 5s
    volumes:
      - /etc/ferrumgate:/etc/ferrumgate
    networks:
      - ferrum
    logging:
      driver: local

  nginx:
    image: nginx:1.23-alpine
    restart: always
    ports:
      - 80:80
      - 443:443
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        delay: 5s
    configs:
      - source: nginx_config
        target: /etc/nginx/conf.d/default.conf
    networks:
      - ferrum
    logging:
      driver: local
  

configs:
  nginx_config:
    file: ./conf/nginx.conf
  

networks:
  ferrum:
    external: true


    
  